# Generated by Django 3.2.11 on 2022-01-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolmanagement',
            old_name='school_code',
            new_name='dise_code',
        ),
    ]
