# Generated by Django 3.2.11 on 2022-01-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_school_code_schoolmanagement_dise_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=20)),
                ('student_class', models.CharField(blank=True, max_length=20)),
                ('roll_no', models.IntegerField(null=True)),
                ('student_type', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolmanagement')),
            ],
        ),
    ]
